# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  view:
    view_response_listener: true
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  body_converter:
    enabled: true
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: false
  exception:
    codes:
      App\HttpExceptions\NotFoundException: 404
    messages:
      App\HttpExceptions\NotFoundException: true
